### ISSUE TITLE
ShowValidationDirective does not work

### ISSUE THREAD

**Issue by deepu105** [jhipster/ng-jhipster#14]
The ShowValidationDirective currently does nothing and probably is very difficult and hacky to get working due to ng2 architecture.
http://stackoverflow.com/questions/34615425/how-to-watch-for-form-changes-in-angular-2

If its not possible to get working without lots of changes then we should remove it.
@sendilkumarn @jdubois what do you think

**Comment by jdubois** [comment]
And I thought Angular 2 was easier and more powerful :-)

Yes let's remove it for the moment. We'll use "normal" validation, and we'll see later if we can improve it.

**Comment by sendilkumarn** [comment]
Yeah we can remove it. We can use what angular2 gives out of box.

**Comment by deepu105** [comment]
May be we can achive the same result by writing a directive on the input itself. Let me explore that later

**Comment by deepu105** [comment]
The directive is removed and the same/better effect is achieved using just css https://github.com/jhipster/generator-jhipster/commit/2205591148743b6b0d05034467ef3fe37f649b75

**Comment by deepu105** [comment]
actually we could have done the same in ng1 as well without a directive. I have no idea why a directive was written for this. @jdubois do you know any background on that?

**Comment by jdubois** [comment]
I would need to go into the Git history, this is very old code.
