### ISSUE TITLE
Add licence headers

### ISSUE THREAD

**Issue by jdubois** [jhipster/ng-jhipster#2]
Can you add licence headers to all your files?

Like we have in `jhipster/jhipster`, for example at:

https://github.com/jhipster/jhipster/blob/master/src/main/java/io/github/jhipster/web/filter/CachingHttpHeadersFilter.java

Now those files are not generated anymore, we should add the licence everywhere.

**Comment by deepu105** [comment]
Sure will do


Thanks & Regards,
Deepu

**Comment by sendilkumarn** [comment]
we can use the same right ?

**Comment by deepu105** [comment]
yes we can use the same


Thanks & Regards,
Deepu

**Comment by jdubois** [comment]
Indeed, they are very generic. It's just to protect our licence.

**Comment by sendilkumarn** [comment]
Okayes 👍 currently I have started the test cases, I will progressively add this .

**Comment by deepu105** [comment]
this is done
